CREATE DATABASE ABC_DATA;

USE ABC_DATA;

CREATE TABLE CUSTOMERS(
CustomerId INT AUTO_INCREMENT PRIMARY KEY,
First_Name VARCHAR (100),
Last_Name VARCHAR (100),
Email VARCHAR(250) UNIQUE NOT NULL
);

INSERT INTO CUSTOMERS(First_Name,Last_Name,Email)
VALUES
('Joe','Doe','Joe.doe@gmail.com');

SELECT * FROM CUSTOMERS;

CREATE TABLE PRODUCTS(
Product_Id INT AUTO_INCREMENT PRIMARY KEY,
Product_Name VARCHAR(100),
Price INT );

INSERT INTO PRODUCTS(Product_Name, Price)
VALUES('Product A', 10.00);

SELECT * FROM PRODUCTS;

CREATE TABLE ORDERS(
Order_Id INT AUTO_INCREMENT PRIMARY KEY,
CustomerId INT ,
Order_Date DATE,
FOREIGN KEY (CustomerId) REFERENCES CUSTOMERS(CustomerId));

INSERT INTO ORDERS(CustomerID,Order_Date)
VALUES
(1,'2023-05-01');

SELECT * FROM ORDERS;

CREATE TABLE ORDER_ITEMS(
Order_Id INT ,
Product_Id INT ,
Quantity INT ,
FOREIGN KEY (Order_Id) REFERENCES ORDERS(Order_Id),
FOREIGN KEY (Product_Id) REFERENCES PRODUCTS(Product_Id));

INSERT INTO ORDER_ITEMS(Order_Id,Product_Id,Quantity)
VALUES
(1,1,2);

SELECT* FROM ORDER_ITEMS



